import '../../../../core/constants/app_icons.dart';
import '../../../../core/router/app_routes.dart';
import '../entities/navigation_section.dart';
import '../entities/shell_destination.dart';

const List<ShellDestination> kDoctorDestinations = [
  ShellDestination(
    id: 'doctor_dashboard',
    route: AppRoutes.doctorDashboard,
    labelKey: 'shell.dashboard',
    icon: AppIcons.dashboard,
    selectedIcon: AppIcons.dashboardActive,
    section: ShellNavSection.main,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/dashboard'],
    sortOrder: 10,
  ),
  ShellDestination(
    id: 'doctor_queue',
    route: AppRoutes.queue,
    labelKey: 'shell.queue',
    icon: AppIcons.queue,
    selectedIcon: AppIcons.queueActive,
    section: ShellNavSection.main,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/queue'],
    sortOrder: 20,
  ),
  ShellDestination(
    id: 'doctor_patients',
    route: AppRoutes.patients,
    labelKey: 'shell.patients',
    icon: AppIcons.patients,
    selectedIcon: AppIcons.patientsActive,
    section: ShellNavSection.patients,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/patients', '/patients'],
    sortOrder: 30,
  ),
  ShellDestination(
    id: 'doctor_prescriptions',
    route: AppRoutes.prescriptions,
    labelKey: 'shell.prescriptions',
    icon: AppIcons.prescriptions,
    selectedIcon: AppIcons.prescriptionsActive,
    section: ShellNavSection.patients,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/prescriptions', '/prescriptions'],
    sortOrder: 40,
  ),
  ShellDestination(
    id: 'doctor_reports',
    route: AppRoutes.reports,
    labelKey: 'shell.reports',
    icon: AppIcons.reports,
    selectedIcon: AppIcons.reportsActive,
    section: ShellNavSection.management,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/reports'],
    sortOrder: 50,
  ),
  ShellDestination(
    id: 'doctor_leave_days',
    route: AppRoutes.doctorLeaveDays,
    labelKey: 'shell.leave_days',
    icon: AppIcons.calendar,
    selectedIcon: AppIcons.calendar,
    section: ShellNavSection.management,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/doctor-leave-days'],
    sortOrder: 60,
  ),
  ShellDestination(
    id: 'doctor_diagnosis_templates',
    route: AppRoutes.diagnosisTemplates,
    labelKey: 'shell.diagnosis_templates',
    icon: AppIcons.diagnosisTemplates,
    selectedIcon: AppIcons.diagnosisTemplates,
    section: ShellNavSection.management,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/diagnosis-templates'],
    sortOrder: 70,
  ),
  ShellDestination(
    id: 'doctor_questions',
    route: AppRoutes.doctorQuestions,
    labelKey: 'shell.doctor_questions',
    icon: AppIcons.doctorQuestions,
    selectedIcon: AppIcons.doctorQuestions,
    section: ShellNavSection.management,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/doctor-questions'],
    sortOrder: 80,
  ),
  ShellDestination(
    id: 'doctor_profile',
    route: AppRoutes.profile,
    labelKey: 'shell.profile',
    icon: AppIcons.profile,
    selectedIcon: AppIcons.profileActive,
    section: ShellNavSection.account,
    allowedAccountTypes: ['doctor'],
    matchPrefixes: ['/shell/profile'],
    sortOrder: 90,
  ),
];
