import '../../../../core/constants/app_icons.dart';
import '../../../../core/router/app_routes.dart';
import '../entities/navigation_section.dart';
import '../entities/shell_destination.dart';

const List<ShellDestination> kReceptionDestinations = [
  ShellDestination(
    id: 'reception_dashboard',
    route: AppRoutes.reception,
    labelKey: 'shell.reception',
    icon: AppIcons.reception,
    selectedIcon: AppIcons.receptionActive,
    section: ShellNavSection.dailyWork,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    requiredAnyPermissions: [
      'reception.view',
      'reception.appointments.view',
      'reception.queue.view',
      'appointments.view',
      'queue.view',
    ],
    matchPrefixes: ['/shell/reception', '/reception'],
    sortOrder: 10,
  ),
  ShellDestination(
    id: 'reception_appointments',
    route: AppRoutes.appointments,
    labelKey: 'shell.appointments',
    icon: AppIcons.appointments,
    selectedIcon: AppIcons.appointmentsActive,
    section: ShellNavSection.dailyWork,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    requiredAnyPermissions: [
      'reception.appointments.view',
      'appointments.view',
    ],
    matchPrefixes: ['/shell/appointments', '/appointments'],
    sortOrder: 20,
  ),
  ShellDestination(
    id: 'reception_queue',
    route: AppRoutes.receptionQueue,
    labelKey: 'shell.queue',
    icon: AppIcons.queue,
    selectedIcon: AppIcons.queueActive,
    section: ShellNavSection.dailyWork,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    requiredAnyPermissions: [
      'reception.queue.view',
      'queue.view',
      'reception.view',
    ],
    matchPrefixes: ['/shell/reception/queue'],
    sortOrder: 25,
  ),
  ShellDestination(
    id: 'reception_patients',
    route: AppRoutes.patients,
    labelKey: 'shell.patients',
    icon: AppIcons.patients,
    selectedIcon: AppIcons.patientsActive,
    section: ShellNavSection.dailyWork,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    requiredAnyPermissions: ['patients.view'],
    matchPrefixes: ['/shell/patients', '/patients'],
    sortOrder: 30,
  ),
  ShellDestination(
    id: 'reception_financial',
    route: AppRoutes.financial,
    labelKey: 'shell.financial',
    icon: AppIcons.financial,
    selectedIcon: AppIcons.financialActive,
    section: ShellNavSection.finance,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    requiredAnyPermissions: [
      'billing.view',
      'financial.view',
      'reception.payments.create',
    ],
    matchPrefixes: ['/shell/financial'],
    sortOrder: 40,
  ),
  ShellDestination(
    id: 'reception_reports',
    route: AppRoutes.reports,
    labelKey: 'shell.reports',
    icon: AppIcons.reports,
    selectedIcon: AppIcons.reportsActive,
    section: ShellNavSection.management,
    allowedAccountTypes: ['clinic_admin'],
    requiredAnyPermissions: ['reports.view'],
    matchPrefixes: ['/shell/reports'],
    sortOrder: 50,
  ),
  ShellDestination(
    id: 'reception_settings',
    route: AppRoutes.settings,
    labelKey: 'shell.settings',
    icon: AppIcons.settings,
    selectedIcon: AppIcons.settingsActive,
    section: ShellNavSection.management,
    allowedAccountTypes: ['clinic_admin'],
    requiredAnyPermissions: ['settings.view', 'settings.manage'],
    matchPrefixes: ['/shell/settings'],
    sortOrder: 60,
  ),
  ShellDestination(
    id: 'reception_profile',
    route: AppRoutes.profile,
    labelKey: 'shell.profile',
    icon: AppIcons.profile,
    selectedIcon: AppIcons.profileActive,
    section: ShellNavSection.account,
    allowedAccountTypes: ['receptionist', 'clinic_admin'],
    matchPrefixes: ['/shell/profile'],
    sortOrder: 70,
  ),
];
